#!/usr/bin/env bash

set -ex

yarn
env FORCE_COLOR=0 \
  yarn run concurrently \
    --names serve,build \
    --prefix name \
    --kill-others \
    'yarn run serve --no-cache | cat' \
    'yarn run watch:typecheck'
